"""Notice drafting (section 7.4).

CASE FACTS IN, CONDITIONAL TEMPLATE OUT. Not prose from a language model.

Every sentence below is selected by a branch on a structured fact that was measured
during the sweep. Nothing is generated, nothing is embellished, and a fact that was
not observed produces no sentence. The section structure matches `mockNotice` in
Frontend/lib/api.ts, which the UI is already laid out for.

Nothing here is ever delivered to a registrant. Draft -> review -> sign. That is all.
"""

from __future__ import annotations

from datetime import date

from ..models import Evidence, Finding
from ..security import as_utc

# notices.stage (the DB vocabulary, section 4) -> Notice.state (what the frontend reads)
STAGE_DRAFT = "draft"
STAGE_AWAITING_SIGNATURE = "awaiting_signature"
STAGE_SIGNED = "signed"
STAGE_DELIVERED = "delivered"
STAGE_RESOLVED = "resolved"

STAGE_TO_STATE = {
    STAGE_DRAFT: "draft",
    STAGE_AWAITING_SIGNATURE: "reviewed",
    STAGE_SIGNED: "signed",
    STAGE_DELIVERED: "signed",
    STAGE_RESOLVED: "signed",
}

DEMAND_DAYS = 14


def build_case_facts(
    finding: Finding, brand: str, evidence: list[Evidence]
) -> dict[str, str]:
    """The structured facts. Every value is read from a stored row, never invented."""
    first_observed = as_utc(finding.created_at)
    return {
        "registrant_domain": finding.domain,
        "rights_holder": brand,
        "first_observed": (first_observed.date() if first_observed else date.today()).isoformat(),
        "harm_class": finding.reason,
        "permutation_technique": finding.technique or "Unknown",
        "evidence_count": str(len(evidence)),
        "mail_capable": "yes" if finding.mail_capable else "no",
    }


def render_body(
    facts: dict[str, str], finding: Finding, evidence: list[Evidence]
) -> str:
    """Conditional template. Each branch is guarded by a measured fact."""
    domain = facts["registrant_domain"]
    brand = facts["rights_holder"]
    lines: list[str] = [
        "## Notice of Trademark Infringement and Demand to Cease and Desist",
        "",
        f"**To:** the registrant of {domain}",
        f"**From:** {brand}, rights holder",
        f"**Date:** {date.today().isoformat()}",
        "",
        "### 1. Rights asserted",
        f"{brand} is the owner of the mark used throughout the domain and site "
        "identified above.",
        "",
        "### 2. Conduct observed",
        facts["harm_class"] + ".",
    ]

    # Branch: how the lookalike was constructed.
    if facts["permutation_technique"] != "Unknown":
        # Phrased to avoid an article before the technique name — "a Omission" was
        # the first draft and it read like a template, which is the one thing a
        # notice must not do.
        lines.append(
            f"The domain was generated by the {facts['permutation_technique']} "
            "permutation technique applied to the rights holder's registered domain."
        )

    # Branch: the differentiating harm — cited by Google's own AI.
    if finding.ai_overview_cited:
        lines.append(
            "The domain appears as a cited source in Google's AI Overview for queries "
            "about the rights holder, placing it in the answer a user receives before "
            "any search result is shown."
        )

    # Branch: mail capability decides whether phishing is possible at all.
    if finding.mail_capable:
        lines.append(
            "The domain has MX records configured and is capable of sending mail that "
            "appears to originate from the rights holder."
        )
    else:
        lines.append(
            "No mail-exchange records were observed at the time of this notice."
        )

    # Branch: live site versus parked registration.
    if finding.live:
        lines.append("The domain served a live page at the time of observation.")
    elif finding.registered:
        lines.append(
            "The domain is registered and resolves but served no live page at the time "
            "of observation."
        )

    lines += [
        "",
        "### 3. Demand",
        "Cease all use of the mark, disable the identified content, and transfer or "
        f"cancel the registration within {DEMAND_DAYS} days of receipt.",
        "",
        "### 4. Evidence",
        f"{len(evidence)} item(s) attached, each with the search surface, URL and "
        "capture timestamp.",
    ]

    # The evidence list is the record, so it is enumerated rather than summarised.
    for item in evidence:
        captured = as_utc(item.fetched_at)
        stamp = captured.isoformat() if captured else ""
        lines.append(f"- `{item.engine}` — {item.url} — captured {stamp}")

    lines += [
        "",
        "---",
        "_Generated from structured case facts through a conditional template. "
        "Reviewed by a person before signature._",
    ]
    return "\n".join(lines)


def synthetic_envelope_id(notice_id: str) -> str:
    """Local stand-in until Foxit eSign is wired in Phase 7.

    Deliberately prefixed `local_` so a synthetic envelope can never be mistaken for
    a real eSign reference.
    """
    return f"local_{notice_id.replace('-', '')[:16]}"
